### ISSUE TITLE
Inkscape 1.0alpha can't find numpy

### ISSUE THREAD

**Issue by Symbian9** [jnweiger/inkscape-flat-projection#1]
Inkscape: 1.0alpha `9dee831` (AppImage)

- https://inkscape.org/release/inkscape-1.0alpha0/

### Actual behavior

![pic.1](https://i.imgur.com/Kx2c2Oj.png)

I checked my system and found that `numpy` installed, so don't know why it can't detect it

```
$ sudo -H pip3 install numpy
Requirement already satisfied: numpy in /usr/lib/python3/dist-packages
```

P.S.: @probonopd this issue related to Inkscape's AppImage?

**Comment by probonopd** [comment]
Yes. The Inkscape AppImage contains its own Python. Which can be problematic if plugins need Python modules which Inscape itself does not need and hence, not bundle. Plus, Python plugins are entirely broken currently in 1.0 alpha, according to the Inkscape team. I think this can be closed here.
